const EXPEDICOES_API_URL = `${window.BabycareUI.API_URL}/api/expedicoes`;
const ESTOQUE_API_URL = `${window.BabycareUI.API_URL}/api/estoque`;
const el = { side: document.querySelector('#sidebarSearch'), open: document.querySelector('#openSidebarButton'), close: document.querySelector('#closeSidebarButton'), logout: document.querySelector('#logoutButton'), bell: document.querySelector('#notificationButton'), novo: document.querySelector('#newShipmentButton'), search: document.querySelector('#shipmentSearch'), period: document.querySelector('#shipmentPeriod'), body: document.querySelector('#shipmentBody'), empty: document.querySelector('#shipmentEmpty'), count: document.querySelector('#shipmentCount'), today: document.querySelector('#todayShipments'), units: document.querySelector('#todayUnits'), lastDate: document.querySelector('#lastShipmentDate'), lastProduct: document.querySelector('#lastShipmentProduct'), modal: document.querySelector('#shipmentModal'), closeModal: document.querySelector('#closeShipmentModal'), cancel: document.querySelector('#cancelShipment'), form: document.querySelector('#shipmentForm'), product: document.querySelector('#shipmentProduct'), quantity: document.querySelector('#shipmentQuantity'), recipient: document.querySelector('#shipmentRecipient'), destination: document.querySelector('#shipmentDestination'), document: document.querySelector('#shipmentDocument'), reason: document.querySelector('#shipmentReason'), note: document.querySelector('#shipmentNote'), error: document.querySelector('#shipmentError'), submit: document.querySelector('#submitShipment'), available: document.querySelector('#availableStock') };
let rows = [], products = [];
const CHAVES_USUARIO = ['babycareUsuario', 'babycareUser'];
function obterUsuarioSessao() {
    for (const chave of CHAVES_USUARIO) {
        const valores = [localStorage.getItem(chave), sessionStorage.getItem(chave)];
        for (const valor of valores) {
            if (!valor) continue;
            try { const usuario = JSON.parse(valor); if (usuario && typeof usuario === 'object') return usuario; } catch (erro) { /* sessão antiga inválida */ }
        }
    }
    return {};
}
function iniciais(nome) { const partes = String(nome || '').trim().split(/\s+/u).filter(Boolean); return partes.length > 1 ? `${partes[0][0]}${partes[partes.length - 1][0]}`.toUpperCase() : (partes[0]?.slice(0, 2).toUpperCase() || 'U'); }
function perfilExibicao(perfil) { return String(perfil || 'Perfil de acesso').replace(/_/gu, ' ').toLocaleLowerCase('pt-BR').replace(/(^|\s)\S/gu, (letra) => letra.toLocaleUpperCase('pt-BR')); }
function atualizarUsuario() {
    const usuario = obterUsuarioSessao(); const nome = typeof usuario.nome === 'string' && usuario.nome.trim() ? usuario.nome.trim() : 'Usuário Babycare'; const perfil = perfilExibicao(usuario.perfil); const avatar = iniciais(nome);
    ['sidebarUserName', 'topbarUserName'].forEach((id) => { const item = document.getElementById(id); if (item) item.textContent = nome; });
    ['sidebarUserRole', 'topbarUserRole'].forEach((id) => { const item = document.getElementById(id); if (item) item.textContent = perfil; });
    ['sidebarAvatar', 'topbarAvatar'].forEach((id) => { const item = document.getElementById(id); if (item) item.textContent = avatar; });
}
function auth() { return localStorage.getItem('babycareToken') || sessionStorage.getItem('babycareToken'); }
function esc(v) { const d = document.createElement('div'); d.textContent = v ?? ''; return d.innerHTML; }
function num(v) { return window.BabycareUI.formatarNumero(Number(v || 0), 3).replace(/,?0+$/, '').replace(/,$/, ''); }
function date(v) { return v ? window.BabycareUI.formatarDataHora(v) : '—'; }
async function api(url, options = {}) { const r = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${auth()}`, ...(options.headers || {}) } }); const b = await r.json().catch(() => ({})); if (!r.ok) { const x = new Error(b.mensagem || 'Não foi possível concluir a operação.'); x.status = r.status; throw x; } return b; }
function preencherProdutos() { el.product.replaceChildren(new Option('Selecione um produto', '')); products.forEach((p) => el.product.appendChild(new Option(`${p.nome} — ${p.codigo} | saldo: ${num(p.estoqueAtual)}`, p.id))); }
function atualizarSaldo() { const p = products.find((x) => String(x.id) === el.product.value); el.available.hidden = !p; if (p) el.available.textContent = `Saldo disponível: ${num(p.estoqueAtual)} ${p.unidade || 'unidade(s)'}`; }
function filtrados() { const t = el.search.value.trim().toLocaleLowerCase('pt-BR'); const days = { HOJE: 1, '7D': 7, '30D': 30 }[el.period.value]; const now = Date.now(); return rows.filter((x) => { const text = [x.produto, x.codigo, x.destinatario, x.destino, x.documento, x.numeroLote].join(' ').toLocaleLowerCase('pt-BR'); return (!t || text.includes(t)) && (!days || (now - new Date(x.criadoEm).getTime()) <= days * 86400000); }); }
function resumo() { const d = new Date(); d.setHours(0, 0, 0, 0); const hoje = rows.filter((x) => new Date(x.criadoEm) >= d); el.today.textContent = window.BabycareUI.formatarNumero(hoje.length); el.units.textContent = num(hoje.reduce((s, x) => s + Number(x.quantidade || 0), 0)); el.lastDate.textContent = rows[0] ? date(rows[0].criadoEm).split(',')[0] : '—'; el.lastProduct.textContent = rows[0]?.produto || 'Nenhuma expedição registrada'; }
function render() { const list = filtrados(); el.count.textContent = `${list.length} registro(s)`; el.body.replaceChildren(); el.empty.hidden = list.length > 0; list.forEach((x) => { const tr = document.createElement('tr'); tr.innerHTML = `<td>${esc(date(x.criadoEm))}</td><td class="expedicao-produto"><strong>${esc(x.produto)}</strong><small>${esc(x.codigo)}</small></td><td>${esc(x.numeroLote || '—')}</td><td class="expedicao-quantidade">−${esc(num(x.quantidade))}</td><td>${esc(x.destinatario)}</td><td>${esc(x.destino)}</td><td>${esc(x.documento || 'Não informado')}</td><td>${esc(x.responsavel)}</td>`; el.body.appendChild(tr); }); }
function erro(t) { el.error.textContent = t || ''; el.error.hidden = !t; }
function abrir() { el.form.reset(); erro(''); el.available.hidden = true; el.modal.hidden = false; document.body.classList.add('modal-open'); setTimeout(() => el.product.focus(), 0); }
function fechar() { el.modal.hidden = true; document.body.classList.remove('modal-open'); }
async function carregar() { window.BabycareUI.mostrarCarregamento('Carregando expedições...'); try { const [h, s] = await Promise.all([api(EXPEDICOES_API_URL), api(ESTOQUE_API_URL)]); rows = Array.isArray(h.expedicoes) ? h.expedicoes : []; products = Array.isArray(s.produtos) ? s.produtos : []; preencherProdutos(); resumo(); render(); } catch (x) { if ([401, 403].includes(x.status)) { location.href = '/pages/login.html'; return; } el.count.textContent = 'Erro ao carregar'; el.empty.hidden = false; el.empty.textContent = x.message; window.BabycareUI.mostrarToast(x.message, 'error'); } finally { window.BabycareUI.esconderCarregamento(); } }
async function enviar(ev) { ev.preventDefault(); const p = products.find((x) => String(x.id) === el.product.value); if (!p) return erro('Selecione um produto.'); const quantidade = Number(el.quantity.value); if (!Number.isFinite(quantidade) || quantidade <= 0) return erro('Informe uma quantidade maior que zero.'); if (!el.recipient.value.trim()) return erro('Informe o destinatário.'); if (!el.destination.value.trim()) return erro('Informe o destino.'); if (Number(p.estoqueAtual) < quantidade) return erro(`Estoque insuficiente. Disponível: ${num(p.estoqueAtual)}.`); el.submit.disabled = true; erro(''); try { await api(EXPEDICOES_API_URL, { method: 'POST', body: JSON.stringify({ tipo: 'SAIDA', produtoId: Number(p.id), quantidade, destinatario: el.recipient.value.trim(), destino: el.destination.value.trim(), documento: el.document.value.trim() || null, motivo: el.reason.value, observacao: el.note.value.trim() || null }) }); fechar(); window.BabycareUI.mostrarToast('Expedição registrada e estoque atualizado.'); await carregar(); } catch (x) { erro(x.message); } finally { el.submit.disabled = false; } }
function configurar() { atualizarUsuario();[el.search, el.period].forEach((x) => x.addEventListener('input', render)); el.product.addEventListener('change', atualizarSaldo); el.novo.addEventListener('click', abrir); el.closeModal.addEventListener('click', fechar); el.cancel.addEventListener('click', fechar); el.form.addEventListener('submit', enviar); el.modal.addEventListener('click', (x) => { if (x.target === el.modal) fechar(); }); document.addEventListener('keydown', (x) => { if (x.key === 'Escape' && !el.modal.hidden) fechar(); }); el.open?.addEventListener('click', () => document.body.classList.add('sidebar-open')); el.close?.addEventListener('click', () => document.body.classList.remove('sidebar-open')); document.querySelectorAll('.nav-link').forEach((x) => x.addEventListener('click', () => document.body.classList.remove('sidebar-open'))); el.side?.addEventListener('input', () => { const t = el.side.value.toLocaleLowerCase('pt-BR'); document.querySelectorAll('.main-nav .nav-link').forEach((x) => x.hidden = Boolean(t) && !x.textContent.toLocaleLowerCase('pt-BR').includes(t)); }); el.bell?.addEventListener('click', () => window.BabycareUI.mostrarToast(rows.length ? `${rows.length} expedição(ões) carregada(s).` : 'Nenhuma expedição registrada.')); el.logout?.addEventListener('click', () => { localStorage.removeItem('babycareToken'); sessionStorage.removeItem('babycareToken'); location.href = '/pages/login.html'; }); }
window.addEventListener('load', () => { configurar(); carregar(); });
